name: Deploy NeuroStore
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd /home/AdminDeveloper/Neurostore_Demo
            git fetch origin
            git reset --hard origin/main
            echo "Building frontend..."
            sudo rm -rf /home/AdminDeveloper/Neurostore_Demo/Neurostore_Demo-main/Frontend/frontend/dist
            cd Neurostore_Demo-main/Frontend/frontend
            npm run build
            echo "Copying to static..."
            sudo rm -rf /var/www/html/*
            sudo cp -r dist/* /var/www/html/
            sudo chmod -R 755 /var/www/html
            sudo chown -R www-data:www-data /var/www/html
            echo "Restarting backend..."
            pm2 restart demo-app --update-env
            pm2 save
            echo "Restarting Nginx..."
            sudo systemctl restart nginx
            echo "Deployment complete!"
